function [ A ] = UpdateX0( Data,DictMat,t )

hRt1 = @(x) D1'*x;
tolA = 1e-3;
[A,x_debias,objective,times,debias_start,mses,max_svd] =TwIST(Data,DictMat,t, ...
         'Lambda', 2.2, ...
       'Debias',0,...
         'AT', hRt1, ... 
         'Monotone',1,...
       'Sparse', 1,...
         'Initialization',0,...
         'StopCriterion',1,...
       	 'ToleranceA',tolA,...
        'Verbose', 1);

end

